export const keyBoardRows = [
    {char:'W', type:''},
    {char:'E', type:''},
    {char:'R', type:''},
    {char:'T', type:''},
    {char:'Y', type:''},
    {char:'U', type:''},
    {char:'I', type:''},
    {char:'O', type:''},
    {char:'P', type:''},
    {char:'A', type:''},
    {char:' ', type:''},
    {char:'S', type:''},
    {char:'D', type:''},
    {char:'F', type:''},
    {char:'G', type:''},
    {char:'H', type:''},
    {char:'J', type:''},
    {char:'K', type:''},
    {char:'L', type:''},
    {char:'Enter', type:''},
    {char:'Z', type:''},
    {char:'X', type:''},
    {char:'C', type:''},
    {char:'V', type:''},
    {char:'B', type:''},
    {char:'N', type:''},
    {char:'M', type:''},
    {char:'Backspace', type:''},
]