import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { Toaster } from "react-hot-toast";
import Provider from "./_trpc/Provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} w-full  h-full dark:bg-[url(/pattern-background-desktop-dark.svg)] bg-[url(/pattern-background-desktop-light.svg)] dark:bg-darkNavy`} >
         <Provider>
          <Toaster />
         {children}
         </Provider>
      </body>
    </html>
  );
}
